BEGIN TRY

BEGIN TRAN;

-- AlterColumn
ALTER TABLE [dbo].[EPickShipment] ALTER COLUMN [epickOrderId] NVARCHAR(1000) NULL;
ALTER TABLE [dbo].[EPickShipment] ALTER COLUMN [senderCode] NVARCHAR(1000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
